global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['jenkins:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']